/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'client' : IDL.Text,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'technologies' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [PortfolioItem],
      [],
    ),
  'addService' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Service],
      [],
    ),
  'checkAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'deletePortfolioItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'listPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ContactMessage],
      [],
    ),
  'updatePortfolioItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'client' : IDL.Text,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'technologies' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [PortfolioItem],
        [],
      ),
    'addService' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Service],
        [],
      ),
    'checkAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'deletePortfolioItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteService' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'listContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'listPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ContactMessage],
        [],
      ),
    'updatePortfolioItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };