/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface PortfolioItem {
  'id' : bigint,
  'client' : string,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'technologies' : Array<string>,
  'category' : string,
}
export interface Service {
  'id' : bigint,
  'title' : string,
  'icon' : string,
  'description' : string,
  'benefits' : Array<string>,
}
export interface _SERVICE {
  'addPortfolioItem' : ActorMethod<
    [string, string, bigint, string, Array<string>, string],
    PortfolioItem
  >,
  'addService' : ActorMethod<[string, string, string, Array<string>], Service>,
  'checkAdminCredentials' : ActorMethod<[string, string], boolean>,
  'deletePortfolioItem' : ActorMethod<[bigint], boolean>,
  'deleteService' : ActorMethod<[bigint], boolean>,
  'listContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'listPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string, string],
    ContactMessage
  >,
  'updatePortfolioItem' : ActorMethod<
    [bigint, string, string, bigint, string, Array<string>, string],
    boolean
  >,
  'updateService' : ActorMethod<
    [bigint, string, string, string, Array<string>],
    boolean
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];